import 'the-new-css-reset/css/reset.css'
import type { Metadata } from 'next'
import { Noto_Color_Emoji } from 'next/font/google'
import { RootLayout } from '@/components/RootLayout'

const notoColorEmoji = Noto_Color_Emoji({
  weight: '400',
  subsets: ['emoji'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${notoColorEmoji.className}`}>
        <RootLayout>{children}</RootLayout>
      </body>
    </html>
  )
}
