import { Oshimen } from '@/oshimen/oshimen'

export const oshimens: Oshimen[] = [
  {
    id: 'yuki_sakuna',
    name: '結城さくな',
    emoji: '🐾',
    birthday: { month: 12, day: 2 },
    shortDescription: 'ｻｸﾀﾝ... ｶﾜｲｲﾈ...',
    description: 'やっぱ結城さくななんだよなぁ〜〜〜〜〜〜〜❗❗❗❗❗❗❗',
    tweetId: '1874123244867031448',
    type: 'vtuber',
    omoideCount: 0,
  },
  {
    id: 'kuwo_on',
    name: '玖遠いのり',
    emoji: '🍼',
    birthday: { month: 9, day: 18 },
    shortDescription: 'ｸｵﾝﾁｬﾝ... キングサリのベイビーブルーさん。かわいい。',
    description:
      'こんなんどう見てもかわいい。あらゆるところがかわいい。172cmと高身長で、たまにバブでたまにお姉さんなところもかわいい。何もかもが好き。',
    tweetId: '1997642894807568526',
    type: 'idol',
    omoideCount: 200,
  },
  {
    id: 'uni_uni',
    name: '雲丹うに',
    emoji: '🍜',
    birthday: { month: 2, day: 15 },
    shortDescription: 'ｳﾆﾁｬﾝ... #うにらーめん',
    description:
      'やはり雲丹うになんですよ、雲丹うに。ｵﾖﾒｻﾝ...です。ミラミラの音楽で顔面鍵盤くんになって、うにちゃんと限界トークするのが楽しいんだよなぁ。',
    tweetId: '1682746728460750853',
    type: 'idol',
    omoideCount: 399,
  },
  {
    id: 'nir',
    name: 'NiR',
    emoji: '💎',
    birthday: { month: 1, day: 30 },
    shortDescription: 'ｵﾆﾙｻﾝ...',
    description:
      'やはりｵﾆﾙｻﾝ...なんだよなぁ...。限界オタクなところも良い。いつも楽しい。いつもかわいい。',
    tweetId: '1814957022355579164',
    type: 'idol',
    omoideCount: 190,
  },
  {
    id: 'mayuri',
    name: '仔羽まゆり',
    emoji: '👼',
    birthday: { month: 6, day: 26 },
    shortDescription: 'ﾏﾕﾘﾁｬﾝ... ｶﾜｲｲﾈ...',
    description:
      'やはりﾏﾕﾘﾁｬﾝ...妹のようにｶﾜｲｲﾈ...ﾏﾕﾘﾁｬﾝ...。いつも笑顔で、いつもかわいい。守りたいこの笑顔。',
    tweetId: '1846154507270635774',
    type: 'idol',
    omoideCount: 128,
  },
  {
    id: 'lilx_usaki',
    name: '李縷さき',
    emoji: '🦭',
    birthday: { month: 8, day: 2 },
    shortDescription: 'ｻｷﾁｬﾝ... ｶﾜｲｲﾈ...',
    description:
      '最近、りるさきが気になってるんですよね。もやしくん呼びが可愛すぎる。りるさきはいいぞ。',
    tweetId: '1847257456944292140',
    type: 'idol',
    omoideCount: 56,
  },
  {
    id: 'rikka',
    name: '六椛',
    emoji: '🤍',
    birthday: { month: 3, day: 21 },
    shortDescription: 'ﾘｯｹﾁｪﾝ... ｶﾜｲｲﾈ...',
    description:
      'やはりﾘｯｹﾁｪﾝ... ｶﾜｲｲﾈ...。六椛ちゃんはいいぞ。いつも笑顔で、いつもかわいい。最高だね。',
    tweetId: '1902688812695966070',
    type: 'idol',
    omoideCount: 26,
  },
  {
    id: 'horie',
    name: '堀江晶太',
    emoji: '🎸',
    birthday: { month: 5, day: 31 },
    shortDescription: 'やっぱ堀江晶太なんだよな〜〜〜〜',
    description:
      'やっぱ堀江晶太なんだよな〜〜〜〜。おまえらも堀江の曲を聴け。堀江曲からしか得られない成分がある。',
    tweetId: '1509887009380499457',
    type: 'bassist',
    omoideCount: 0,
  },
  {
    id: 'rin',
    name: 'リンドウ=リン',
    emoji: '🐟',
    birthday: { month: 7, day: 14 },
    shortDescription: 'ﾘﾝﾁｬﾝ... ｶﾜｲｲﾈ...',
    description: 'やはりリンドウ=リン、お顔が良すぎる。良すぎるってマジで。',
    tweetId: '1848325062748946754',
    type: 'idol',
    omoideCount: 10,
  },
  {
    id: 'kino',
    name: '佳凪きの',
    emoji: '📝',
    birthday: { month: 1, day: 2 },
    shortDescription: 'ｷﾉﾁｬﾝ... ｶﾜｲｲﾈ...',
    description:
      'おまえら、佳凪きのちゃんのこと好きだろ？noteは読んだか？あれは読んだ方が良いぞ。',
    tweetId: '1847210316666741024',
    type: 'idol',
    omoideCount: 10,
  },
  {
    id: 'nanami',
    name: '立花菜波',
    emoji: '⛰️',
    birthday: { month: 1, day: 30 },
    shortDescription: 'ﾅﾅﾐﾁｬﾝ... ｶｯｺｲｲﾈ...',
    description: '所沢住んでる人はみんな菜波推しです。',
    tweetId: '1858119803015512143',
    type: 'idol',
    omoideCount: 0,
  },
  {
    id: 'garumu',
    name: 'がるむ',
    emoji: '💙',
    birthday: { month: 11, day: 29 },
    shortDescription: 'ｶﾞﾙﾑﾁｬﾝ... ｶﾜｲｲﾈ...',
    description: 'がるむちゃんのフード姿で救われる命があります。',
    tweetId: '1865383612050514413',
    type: 'idol',
    omoideCount: 10,
  },
  {
    id: 'aoiuta',
    name: '葵うた',
    emoji: '🎤',
    birthday: { month: 11, day: 8 },
    shortDescription: 'ｺﾝﾅｶｵﾆﾅｯﾁｬｯﾃ... ｶﾜｲｿｳ...',
    description: 'かずき__________',
    tweetId: '1845439273811746884',
    type: 'idol',
    omoideCount: 11,
  },
  {
    id: 'hoshijima',
    name: '星島ゆい',
    emoji: '🪽',
    birthday: { month: 5, day: 21 },
    shortDescription: '星島ゆいは神、デカリボンを崇めろ',
    description:
      'デカリボンは神、可愛すぎるだろ。デカリボンによって救われる命はあります。',
    tweetId: '1920084876067549251',
    type: 'idol',
    omoideCount: 5,
  },
  {
    id: 'julia',
    name: '久遠じゅりあ',
    emoji: '🍺',
    birthday: { month: 12, day: 4 },
    shortDescription: 'じゅちゃん... かわいいね...',
    description: 'たまに出る広島弁が可愛すぎて横転です。',
    tweetId: '1925870820896702830',
    type: 'idol',
    omoideCount: 12,
  },
  {
    id: 'kariwori',
    name: 'カリヲリ',
    emoji: '🪽',
    birthday: { month: 7, day: 31 },
    shortDescription: 'ｶﾘｦﾘ... ｶﾜｲｲﾈ...',
    description: 'カリヲリ〜〜〜〜〜〜〜〜！！！！！！！！！',
    tweetId: '1929147951953133970',
    type: 'idol',
    omoideCount: 6,
  },
  {
    id: 'emiru',
    name: '栗原えみる',
    emoji: '🎀',
    birthday: { month: 2, day: 16 },
    shortDescription: 'えみーる... 結婚してくれ〜でも結婚キャンセル界隈...',
    description:
      'えみーるは結婚してくれ〜〜〜〜〜と言うと結婚してくれないので結婚キャンセル界隈と言われています。お姉さんなところも可愛すぎて限界オタクになってしまう。',
    tweetId: '1930621902839861539',
    type: 'idol',
    omoideCount: 3,
  },
  {
    id: 'minami_miu',
    name: '未波みう',
    emoji: '🌅',
    birthday: { month: 11, day: 6 },
    shortDescription: 'みうちゃん... おはみゅしてね...',
    description:
      '「おはみゅ」してと本人はお願いしてました。朝一番のみうちゃんの「おはみゅ」で今日も一日頑張れる。そんな太陽のように明るいみうちゃんが大好きです。',
    tweetId: '1950330505502576823',
    type: 'idol',
    omoideCount: 11,
  },
  {
    id: 'yonagi_sena',
    name: '夜凪せな',
    emoji: '🌙',
    birthday: { month: 3, day: 4 },
    shortDescription: 'せなちゃん... 夜空のように美しい...',
    description:
      '夜の静寂を思わせる美しい名前のせなちゃん。月のアイコンがよく似合う、神秘的な魅力のアイドル。',
    tweetId: '1937497951502524604',
    type: 'idol',
    omoideCount: 5,
  },
  {
    id: 'fujisaki_momo',
    name: '藤咲もも',
    emoji: '🍑',
    birthday: { month: 12, day: 8 },
    shortDescription: 'ﾓﾓﾁｬﾝ... ももとにこにこ...',
    description:
      'ももちゃん、可愛すぎてにこにこした笑顔が良すぎてもう大好き止まりません。',
    tweetId: '1987524211137794278',
    type: 'idol',
    omoideCount: 3,
  },
  {
    id: 'tsukikage_rei',
    name: '月影れい',
    emoji: '🌙',
    birthday: { month: 9, day: 13 },
    shortDescription: 'ﾚｲﾁｬﾝ...俺はリンクラインを見ろおじさんだよ...',
    description:
      'リンクラインの現場は最高だしれいちゃんは良すぎてもう最高なのでみんな見てくれ。',
    tweetId: '1970837418468413593',
    type: 'idol',
    omoideCount: 5,
  },
  {
    id: 'yukine_tnla',
    name: 'ユキネ',
    emoji: '❄️',
    birthday: { month: 12, day: 14 },
    shortDescription: 'ﾕｷﾈﾁｬﾝ...ｵﾈｴﾁｬﾝと結婚したら義妹にしてあげるね...',
    description:
      '「はじめまして。先日オタクにチェキを代行してもらったもやしキングです。お姉ちゃんから来ました。」',
    tweetId: '1999128277999665378',
    type: 'idol',
    omoideCount: 3,
  },
  {
    id: 'sumiha_tnla',
    name: 'スミハ',
    emoji: '🩷',
    birthday: { month: 11, day: 4 },
    shortDescription: 'ｽｰﾁｬﾝ... よちよちしてあげるね... 黒帯二段...?',
    description:
      'スーちゃんはトナリアのピンク最年少なのでオタクがよちよちしてあげますね〜〜〜〜。あっ、空手黒帯二段。よちよちされるのはこちらでした。シナモンと川になってスーちゃんの視界の端で生きたい。',
    tweetId: '2052728127022150011',
    type: 'idol',
    omoideCount: 10,
  },
  {
    id: 'runon_tnla',
    name: 'ルノン',
    emoji: '🦕',
    birthday: { month: 1, day: 30 },
    shortDescription: 'ﾙﾉﾝﾁｬﾝ... 今日の脳直ツイートまだ...?',
    description:
      'ルノンの脳直ツイートを毎朝吸わないと一日が始まらない体になりました。思案ブルーの思案がTwitter経由でオタクの脚に流れ込んでくる。これがるんぽこのある生活。ルノン、今日もツイートしてくれてありがとう。',
    tweetId: '1680907730499043328',
    type: 'idol',
    omoideCount: 10,
  },
  {
    id: 'rukawa_luca',
    name: '瑠川るか',
    emoji: '💙',
    birthday: { month: 12, day: 21 },
    shortDescription: 'ﾙｶﾁｬﾝ... 鼓膜も脚みそも全部あげるね...',
    description:
      'パスラジのデカい音で鼓膜を壊して、瑠川るかのお顔で視力を壊して、最後にダンスで脚みそを焼いてもらう。五感のうち三つをるかちゃんに差し出しているので、残りの二つもいつでも持っていってください。',
    tweetId: '1952377205125984361',
    type: 'idol',
    omoideCount: 10,
  },
  {
    id: 'pastel_radio_marine',
    name: 'マリン',
    emoji: '🐥',
    birthday: { month: 3, day: 20 },
    shortDescription: 'ﾏﾘﾝﾁｬﾝ... その黒髪に住民票置いていい...?',
    description:
      'マリンちゃんの黒髪スーパーロング、一本ずつに番地を振って住民票を置きたい。パスラジの水色でLABOnes.のメイドで感性まで美しいので、もうマリンちゃんのビーカーの底に沈殿する不純物でいいです。',
    tweetId: '1952403679488921848',
    type: 'idol',
    omoideCount: 10,
  },
  {
    id: 'amesun_luvrix',
    name: 'あめすん',
    emoji: '💤',
    birthday: { month: 4, day: 14 },
    shortDescription: 'ｱﾒｽﾝ... 脚内アンテナが受信してるよ...',
    description:
      'あめすんのブルーシグナルを受信するため、脚内にアンテナを増設しました。ダンスするあめすんの残像を永久保存し、アイスと卵焼きをお供えしています。ノイズでもいいので、あめすんの電波を常に感じていたい。',
    tweetId: '2049842719984644266',
    type: 'idol',
    omoideCount: 10,
  },
  {
    id: 'togari_yuma',
    name: '兎仮ゆま',
    emoji: '🧠',
    birthday: { month: 2, day: 26 },
    shortDescription: 'ﾕﾏﾁｬﾝ... 網膜の裏側から尖ってきてる...',
    description:
      '兎仮ゆま、もう網膜の裏とか脚みそのしわの間とか、普通は人が入らないところ全部にいる。「誰よりも、尖ってこーぜ♡」と言われたので毎日脚みそを削って尖らせています。ゆまちゃん、テナント料は永久無料です。',
    tweetId: '2048016678378684858',
    type: 'idol',
    omoideCount: 10,
  },
]
