import { Oshimen } from '@/oshimen/oshimen'

export const oshimens: Oshimen[] = [
  {
    id: 'yuki_sakuna',
    name: '結城さくな',
    emoji: '🐾',
    birthday: { month: 12, day: 2 },
    shortDescription: 'ｻｸﾀﾝ... ｶﾜｲｲﾈ...',
    description: 'やっぱ結城さくななんだよなぁ〜〜〜〜〜〜〜❗❗❗❗❗❗❗',
    tweetId: '1874123244867031448',
    type: 'vtuber',
    omoideCount: 0,
  },
  {
    id: 'kuwo_on',
    name: '玖遠いのり',
    emoji: '🍼',
    birthday: { month: 9, day: 18 },
    shortDescription: 'ｸｵﾝﾁｬﾝ... キングサリのベイビーブルーさん。かわいい。',
    description:
      'こんなんどう見てもかわいい。あらゆるところがかわいい。172cmと高身長で、たまにバブでたまにお姉さんなところもかわいい。何もかもが好き。',
    tweetId: '1956340857315238316',
    type: 'idol',
    omoideCount: 200,
  },
  {
    id: 'uni_uni',
    name: '雲丹うに',
    emoji: '🍜',
    birthday: { month: 2, day: 15 },
    shortDescription: 'ｳﾆﾁｬﾝ... #うにらーめん',
    description:
      'やはり雲丹うになんですよ、雲丹うに。ｵﾖﾒｻﾝ...です。ミラミラの音楽で顔面鍵盤くんになって、うにちゃんと限界トークするのが楽しいんだよなぁ。',
    tweetId: '1682746728460750853',
    type: 'idol',
    omoideCount: 399,
  },
  {
    id: 'nir',
    name: 'NiR',
    emoji: '💎',
    birthday: { month: 1, day: 30 },
    shortDescription: 'ｵﾆﾙｻﾝ...',
    description:
      'やはりｵﾆﾙｻﾝ...なんだよなぁ...。限界オタクなところも良い。いつも楽しい。いつもかわいい。',
    tweetId: '1814957022355579164',
    type: 'idol',
    omoideCount: 190,
  },
  {
    id: 'chia',
    name: '未白ちあ',
    emoji: '🐹',
    birthday: { month: 2, day: 23 },
    shortDescription: 'ﾁｱﾁｬﾝ... かわいいね。',
    description:
      'やはりﾁｱﾁｬﾝ... かわいいね。ちあにあちあちなので、ぼくは。最近、ちあが可愛すぎて心が苦しいです。ガチで好きなんだなぁ...とね。',
    tweetId: '1837825076810731542',
    type: 'idol',
    omoideCount: 281,
  },
  {
    id: 'mayuri',
    name: '仔羽まゆり',
    emoji: '👼',
    birthday: { month: 6, day: 26 },
    shortDescription: 'ﾏﾕﾘﾁｬﾝ... ｶﾜｲｲﾈ...',
    description:
      'やはりﾏﾕﾘﾁｬﾝ...妹のようにｶﾜｲｲﾈ...ﾏﾕﾘﾁｬﾝ...。いつも笑顔で、いつもかわいい。守りたいこの笑顔。',
    tweetId: '1846154507270635774',
    type: 'idol',
    omoideCount: 128,
  },
  {
    id: 'lilx_usaki',
    name: '李縷さき',
    emoji: '🦭',
    birthday: { month: 8, day: 2 },
    shortDescription: 'ｻｷﾁｬﾝ... ｶﾜｲｲﾈ...',
    description:
      '最近、りるさきが気になってるんですよね。もやしくん呼びが可愛すぎる。りるさきはいいぞ。',
    tweetId: '1847257456944292140',
    type: 'idol',
    omoideCount: 56,
  },
  {
    id: 'rikka',
    name: '六椛',
    emoji: '🤍',
    birthday: { month: 3, day: 21 },
    shortDescription: 'ﾘｯｹﾁｪﾝ... ｶﾜｲｲﾈ...',
    description:
      'やはりﾘｯｹﾁｪﾝ... ｶﾜｲｲﾈ...。六椛ちゃんはいいぞ。いつも笑顔で、いつもかわいい。最高だね。',
    tweetId: '1902688812695966070',
    type: 'idol',
    omoideCount: 26,
  },
  {
    id: 'horie',
    name: '堀江晶太',
    emoji: '🎸',
    birthday: { month: 5, day: 31 },
    shortDescription: 'やっぱ堀江晶太なんだよな〜〜〜〜',
    description:
      'やっぱ堀江晶太なんだよな〜〜〜〜。おまえらも堀江の曲を聴け。堀江曲からしか得られない成分がある。',
    tweetId: '1509887009380499457',
    type: 'bassist',
    omoideCount: 0,
  },
  {
    id: 'hisui',
    name: '月埜ヒスイ',
    emoji: '🌊',
    birthday: { month: 7, day: 23 },
    shortDescription: 'ﾋｽｲﾁｬﾝ... ｶﾜｲｲﾈ...',
    description:
      '月ヒスの水着で夏が始まるって言っても過言じゃない。俺はそう信じている。',
    tweetId: '1820431513567277211',
    type: 'idol',
    omoideCount: 1,
  },
  {
    id: 'rin',
    name: 'リンドウ=リン',
    emoji: '🐟',
    birthday: { month: 7, day: 14 },
    shortDescription: 'ﾘﾝﾁｬﾝ... ｶﾜｲｲﾈ...',
    description: 'やはりリンドウ=リン、お顔が良すぎる。良すぎるってマジで。',
    tweetId: '1848325062748946754',
    type: 'idol',
    omoideCount: 10,
  },
  {
    id: 'kino',
    name: '佳凪きの',
    emoji: '📝',
    birthday: { month: 1, day: 2 },
    shortDescription: 'ｷﾉﾁｬﾝ... ｶﾜｲｲﾈ...',
    description:
      'おまえら、佳凪きのちゃんのこと好きだろ？noteは読んだか？あれは読んだ方が良いぞ。',
    tweetId: '1847210316666741024',
    type: 'idol',
    omoideCount: 10,
  },
  {
    id: 'nanami',
    name: '立花菜波',
    emoji: '⛰️',
    birthday: { month: 1, day: 30 },
    shortDescription: 'ﾅﾅﾐﾁｬﾝ... ｶｯｺｲｲﾈ...',
    description: '所沢住んでる人はみんな菜波推しです。',
    tweetId: '1858119803015512143',
    type: 'idol',
    omoideCount: 0,
  },
  {
    id: 'garumu',
    name: 'がるむ',
    emoji: '💙',
    birthday: { month: 11, day: 29 },
    shortDescription: 'ｶﾞﾙﾑﾁｬﾝ... ｶﾜｲｲﾈ...',
    description: 'がるむちゃんのフード姿で救われる命があります。',
    tweetId: '1865383612050514413',
    type: 'idol',
    omoideCount: 10,
  },
  {
    id: 'aoiuta',
    name: '葵うた',
    emoji: '🎤',
    birthday: { month: 11, day: 8 },
    shortDescription: 'ｺﾝﾅｶｵﾆﾅｯﾁｬｯﾃ... ｶﾜｲｿｳ...',
    description: 'かずき__________',
    tweetId: '1845439273811746884',
    type: 'idol',
    omoideCount: 11,
  },
  {
    id: 'hoshijima',
    name: '星島ゆい',
    emoji: '🪽',
    birthday: { month: 5, day: 21 },
    shortDescription: '星島ゆいは神、デカリボンを崇めろ',
    description:
      'デカリボンは神、可愛すぎるだろ。デカリボンによって救われる命はあります。',
    tweetId: '1920084876067549251',
    type: 'idol',
    omoideCount: 5,
  },
  {
    id: 'julia',
    name: '久遠じゅりあ',
    emoji: '🍺',
    birthday: { month: 12, day: 4 },
    shortDescription: 'じゅちゃん... かわいいね...',
    description: 'たまに出る広島弁が可愛すぎて横転です。',
    tweetId: '1925870820896702830',
    type: 'idol',
    omoideCount: 12,
  },
  {
    id: 'kariwori',
    name: 'カリヲリ',
    emoji: '🪽',
    birthday: { month: 7, day: 31 },
    shortDescription: 'ｶﾘｦﾘ... ｶﾜｲｲﾈ...',
    description: 'カリヲリ〜〜〜〜〜〜〜〜！！！！！！！！！',
    tweetId: '1929147951953133970',
    type: 'idol',
    omoideCount: 6,
  },
  {
    id: 'emiru',
    name: '栗原えみる',
    emoji: '🎀',
    birthday: { month: 2, day: 16 },
    shortDescription: 'えみーる... 結婚してくれ〜でも結婚キャンセル界隈...',
    description:
      'えみーるは結婚してくれ〜〜〜〜〜と言うと結婚してくれないので結婚キャンセル界隈と言われています。お姉さんなところも可愛すぎて限界オタクになってしまう。',
    tweetId: '1930621902839861539',
    type: 'idol',
    omoideCount: 3,
  },
  {
    id: 'minami_miu',
    name: '未波みう',
    emoji: '🌅',
    birthday: { month: 11, day: 6 },
    shortDescription: 'みうちゃん... おはみゅしてね...',
    description:
      '「おはみゅ」してと本人はお願いしてました。朝一番のみうちゃんの「おはみゅ」で今日も一日頑張れる。そんな太陽のように明るいみうちゃんが大好きです。',
    tweetId: '1950330505502576823',
    type: 'idol',
    omoideCount: 11,
  },
  {
    id: 'yonagi_sena',
    name: '夜凪せな',
    emoji: '🌙',
    birthday: { month: 3, day: 4 },
    shortDescription: 'せなちゃん... 夜空のように美しい...',
    description:
      '夜の静寂を思わせる美しい名前のせなちゃん。月のアイコンがよく似合う、神秘的な魅力のアイドル。',
    tweetId: '1937497951502524604',
    type: 'idol',
    omoideCount: 5,
  },
  {
    id: 'kimishima_nagi',
    name: '君島凪',
    emoji: '🐴',
    birthday: { month: 6, day: 15 },
    shortDescription: 'ﾅｷﾞﾁｬﾝ... ｶﾜｲｲﾈ...',
    description:
      'yosugalaの君島凪ちゃん。やばい、やばすぎる。競馬の話をしてる時のなぎちゃんの顔つきで横転です。穏やかな表情から一変して推し馬の話になった瞬間になぎオタクになった。159cmという絶妙な身長も完璧すぎて、いまなぎちゃん以外の女と結婚できないモード入ってる。',
    tweetId: '1889281000171090114',
    type: 'idol',
    omoideCount: 19,
  },
  {
    id: 'fujisaki_momo',
    name: '藤咲もも',
    emoji: '🍑',
    birthday: { month: 12, day: 8 },
    shortDescription: 'ﾓﾓﾁｬﾝ... ももとにこにこ...',
    description:
      'HIBANAで紫を担当カラーとして活動中のももちゃん。明るく笑顔が魅力で、「ももとにこにこ」というハッシュタグでファンに親しまれている。元気でポジティブな性格が特徴で、ライブやSNSでファンとの交流を積極的に行う。紫をイメージカラーに可愛らしいビジュアルで支持を集めている。',
    tweetId: '1991090245379760518',
    type: 'idol',
    omoideCount: 3,
  },
  {
    id: 'tsukikage_rei',
    name: '月影れい',
    emoji: '🌙',
    birthday: { month: 9, day: 13 },
    shortDescription: 'ﾚｲﾁｬﾝ...俺はリンクラインを見ろおじさんだよ...',
    description:
      'linixlineで活動中のれいちゃん。ミステリアスでクールな雰囲気を持ちながら、柔らかい表情が魅力。SNSでは日常のスナップやファッションを投稿し、ファンを引きつける。釣りやアウトドアが趣味で多面的な魅力がある。月影という名前の通り、夜や幻想的なイメージが似合うビジュアル。',
    tweetId: '1972539256255185231',
    type: 'idol',
    omoideCount: 5,
  },
]
