import { Oshimen } from '@/oshimen/oshimen'

export const oshimens: Oshimen[] = [
  {
    id: 'yuki_sakuna',
    name: '結城さくな',
    emoji: '🐾',
    birthday: { month: 12, day: 2 },
    shortDescription: 'ｻｸﾀﾝ... ｶﾜｲｲﾈ...',
    description: 'やっぱ結城さくななんだよなぁ〜〜〜〜〜〜〜❗❗❗❗❗❗❗',
    tweetId: '1874123244867031448',
    type: 'vtuber',
  },
  {
    id: 'kuwo_on',
    name: '玖遠いのり',
    emoji: '🍼',
    birthday: { month: 9, day: 18 },
    shortDescription: 'ｸｵﾝﾁｬﾝ... キングサリのベイビーブルーさん。かわいい。',
    description:
      'こんなんどう見てもかわいい。あらゆるところがかわいい。172cmと高身長で、たまにバブでたまにお姉さんなところもかわいい。何もかもが好き。',
    tweetId: '1937837821315649839',
    type: 'idol',
  },
  {
    id: 'uni_uni',
    name: '雲丹うに',
    emoji: '🍜',
    birthday: { month: 2, day: 15 },
    shortDescription: 'ｳﾆﾁｬﾝ... #うにらーめん',
    description:
      'やはり雲丹うになんですよ、雲丹うに。ｵﾖﾒｻﾝ...です。ミラミラの音楽で顔面鍵盤くんになって、うにちゃんと限界トークするのが楽しいんだよなぁ。',
    tweetId: '1682746728460750853',
    type: 'idol',
  },
  {
    id: 'nir',
    name: 'NiR',
    emoji: '💎',
    birthday: { month: 1, day: 30 },
    shortDescription: 'ｵﾆﾙｻﾝ...',
    description:
      'やはりｵﾆﾙｻﾝ...なんだよなぁ...。限界オタクなところも良い。いつも楽しい。いつもかわいい。',
    tweetId: '1814957022355579164',
    type: 'idol',
  },
  {
    id: 'chia',
    name: '未白ちあ',
    emoji: '🐹',
    birthday: { month: 2, day: 23 },
    shortDescription: 'ﾁｱﾁｬﾝ... かわいいね。',
    description:
      'やはりﾁｱﾁｬﾝ... かわいいね。ちあにあちあちなので、ぼくは。最近、ちあが可愛すぎて心が苦しいです。ガチで好きなんだなぁ...とね。',
    tweetId: '1837825076810731542',
    type: 'idol',
  },
  {
    id: 'mayuri',
    name: '仔羽まゆり',
    emoji: '👼',
    birthday: { month: 6, day: 26 },
    shortDescription: 'ﾏﾕﾘﾁｬﾝ... ｶﾜｲｲﾈ...',
    description:
      'やはりﾏﾕﾘﾁｬﾝ...妹のようにｶﾜｲｲﾈ...ﾏﾕﾘﾁｬﾝ...。いつも笑顔で、いつもかわいい。守りたいこの笑顔。',
    tweetId: '1846154507270635774',
    type: 'idol',
  },
  {
    id: 'lilx_usaki',
    name: '李縷さき',
    emoji: '🦭',
    birthday: { month: 8, day: 2 },
    shortDescription: 'ｻｷﾁｬﾝ... ｶﾜｲｲﾈ...',
    description:
      '最近、りるさきが気になってるんですよね。もやしくん呼びが可愛すぎる。りるさきはいいぞ。',
    tweetId: '1847257456944292140',
    type: 'idol',
  },
  {
    id: 'rikka',
    name: '六椛',
    emoji: '🤍',
    birthday: { month: 3, day: 21 },
    shortDescription: 'ﾘｯｹﾁｪﾝ... ｶﾜｲｲﾈ...',
    description:
      'やはりﾘｯｹﾁｪﾝ... ｶﾜｲｲﾈ...。六椛ちゃんはいいぞ。いつも笑顔で、いつもかわいい。最高だね。',
    tweetId: '1902688812695966070',
    type: 'idol',
  },
  {
    id: 'horie',
    name: '堀江晶太',
    emoji: '🎸',
    birthday: { month: 5, day: 31 },
    shortDescription: 'やっぱ堀江晶太なんだよな〜〜〜〜',
    description:
      'やっぱ堀江晶太なんだよな〜〜〜〜。おまえらも堀江の曲を聴け。堀江曲からしか得られない成分がある。',
    tweetId: '1509887009380499457',
    type: 'bassist',
  },
  {
    id: 'hisui',
    name: '月埜ヒスイ',
    emoji: '🌊',
    birthday: { month: 7, day: 23 },
    shortDescription: 'ﾋｽｲﾁｬﾝ... ｶﾜｲｲﾈ...',
    description:
      '月ヒスの水着で夏が始まるって言っても過言じゃない。俺はそう信じている。',
    tweetId: '1820431513567277211',
    type: 'idol',
  },
  {
    id: 'rin',
    name: 'リンドウ=リン',
    emoji: '🐟',
    birthday: { month: 7, day: 14 },
    shortDescription: 'ﾘﾝﾁｬﾝ... ｶﾜｲｲﾈ...',
    description: 'やはりリンドウ=リン、お顔が良すぎる。良すぎるってマジで。',
    tweetId: '1848325062748946754',
    type: 'idol',
  },
  {
    id: 'kino',
    name: '佳凪きの',
    emoji: '📝',
    birthday: { month: 1, day: 2 },
    shortDescription: 'ｷﾉﾁｬﾝ... ｶﾜｲｲﾈ...',
    description:
      'おまえら、佳凪きのちゃんのこと好きだろ？noteは読んだか？あれは読んだ方が良いぞ。',
    tweetId: '1847210316666741024',
    type: 'idol',
  },
  {
    id: 'nanami',
    name: '立花菜波',
    emoji: '⛰️',
    birthday: { month: 1, day: 30 },
    shortDescription: 'ﾅﾅﾐﾁｬﾝ... ｶｯｺｲｲﾈ...',
    description: '所沢住んでる人はみんな菜波推しです。',
    tweetId: '1858119803015512143',
    type: 'idol',
  },
  {
    id: 'garumu',
    name: 'がるむ',
    emoji: '💙',
    birthday: { month: 11, day: 29 },
    shortDescription: 'ｶﾞﾙﾑﾁｬﾝ... ｶﾜｲｲﾈ...',
    description: 'がるむちゃんのフード姿で救われる命があります。',
    tweetId: '1865383612050514413',
    type: 'idol',
  },
  {
    id: 'aoiuta',
    name: '葵うた',
    emoji: '🎤',
    birthday: { month: 11, day: 8 },
    shortDescription: 'ｺﾝﾅｶｵﾆﾅｯﾁｬｯﾃ... ｶﾜｲｿｳ...',
    description: 'かずき__________',
    tweetId: '1845439273811746884',
    type: 'idol',
  },
  {
    id: 'hoshijima',
    name: '星島ゆい',
    emoji: '🪽',
    birthday: { month: 5, day: 21 },
    shortDescription: '星島ゆいは神、デカリボンを崇めろ',
    description:
      'デカリボンは神、可愛すぎるだろ。デカリボンによって救われる命はあります。',
    tweetId: '1920084876067549251',
    type: 'idol',
  },
  {
    id: 'julia',
    name: '久遠じゅりあ',
    emoji: '🍺',
    birthday: { month: 12, day: 4 },
    shortDescription: 'じゅちゃん... かわいいね...',
    description: 'たまに出る広島弁が可愛すぎて横転です。',
    tweetId: '1925870820896702830',
    type: 'idol',
  },
  {
    id: 'kariwori',
    name: 'カリヲリ',
    emoji: '🪽',
    birthday: { month: 7, day: 31 },
    shortDescription: 'ｶﾘｦﾘ... ｶﾜｲｲﾈ...',
    description: 'カリヲリ〜〜〜〜〜〜〜〜！！！！！！！！！',
    tweetId: '1929147951953133970',
    type: 'idol',
  },
  {
    id: 'emiru',
    name: '栗原えみる',
    emoji: '🎀',
    birthday: { month: 2, day: 16 },
    shortDescription: 'えみーる... 結婚してくれ〜でも結婚キャンセル界隈...',
    description:
      'えみーるは結婚してくれ〜〜〜〜〜と言うと結婚してくれないので結婚キャンセル界隈と言われています。お姉さんなところも可愛すぎて限界オタクになってしまう。',
    tweetId: '1930621902839861539',
    type: 'idol',
  },
]
